### ISSUE TITLE
get_files() issues an incorrect query

### ISSUE THREAD

**Issue by umaxfun** [reise69/directus-py-sdk#1]
https://github.com/reise69/directus-py-sdk/blob/d0d1618e324097ce828edf3f955ab40653e8f720/directus_sdk_py/main.py#L289 here the resulting path becomes "//files":

```py
{'errors': [{'message': "Route [//files](https://files/) doesn't exist.", 'extensions': {'code': 'ROUTE_NOT_FOUND', 'path': '//files'}}]}
```

When changing to `return self.search("files", query=query, **kwargs)`, everything works well.

**Comment by umaxfun** [comment]
The problem seems to be with url stated with the trailing slash. We can use https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urljoin to avoid it completely.

**Comment by reise69** [comment]
@umaxfun 

Thanks for your report and help, modification is now online
