### ISSUE TITLE
Error calling client.get_item

### ISSUE THREAD

**Issue by Psychedelic-Engineering** [reise69/directus-py-sdk#2]
When i call 
`client.get_item(collection_name, item_id)`
i receive an error 
`{'error': "No data found for this request : 'data'"}`
, while 
`client.get_items(collection_name, {"query": {"filter": {"id": {"_eq": "1"}}}})` 
works like expected. 

In my directus-logs i found, that the first command calls the endpoint
`SEARCH /items/collection_name/1`
, which doesn't exist. Shouldn't it be a GET request 
`GET /items/collection_name/1`
for getting a single item?  

Calling the get method directly works fine:
`client.get(f"/items/{collection_name}/{item_id}")`

By the way, thanks for this library!

**Comment by reise69** [comment]
@Psychedelic-Engineering 

Thanks for your report and your help, i correct this issue.
